" Retirer la compatibilité avec VI
set nocompatible

" Barre espace > Page down
nmap <Space> <PageDown>

" Active la numérotation des lignes
set number

" Active les numéros de lignes relatif par rapport à la positoin actuel
set relativenumber

" Active la coloration syntaxique
syntax on

" Active l indentation syntaxique
set smartindent

" Show current mode
set showmode

" Show command being executed
set showcmd

" Always show status line
set laststatus=2"
set statusline+=col:\ %c,

" Enhance command line completion
set wildmenu

" Allow mouse use in vim
set mouse=a

" Briefly show matching braces, parens, etc
set showmatch

" Enable line wrapping
set wrap

" Wrap on column 80
set textwidth=79

" Disable preview window on completion
set completeopt=longest,menuone

" Highlight current line
set cursorline

" Use UTF-8 as the default text encoding
set encoding=utf-8

" Try to set right locale
try
	lang fr_FR
catch
endtry

" Indentation automatique
set autoindent

" Indentation intelligente
set smartindent

" Tabulation = 4 espaces
set tabstop=4
set shiftwidth=4

" affichage des 80 colones
set colorcolumn=80

"------------------------------------------------
" Search options
"------------------------------------------------

" Ignore case on search
set ignorecase

" Ignore case unless there is an uppercase letter in the pattern
set smartcase

" Move cursor to the matched string
set incsearch

" Indentation
filetype indent on


"------------------------------------------------
" Raccourci perso
"------------------------------------------------

" Correction d'indentation automatique < ;i >
nmap <silent> ;i gg=G

" Split screen horiz and vert, prompt for file, and open
" ala gosmacs visit-file or GNU find-file-other-window
map <C-X><C-V> :vsplit 
map <C-X><C-H> :sp 


