" Retirer la compatibilité avec VI
set nocompatible

" Barre espace > Page down
nmap <Space> <PageDown>

" Active la numérotation des lignes
set number

" Active les numéros de lignes relatif par rapport à la positoin actuel
set relativenumber

" Active la coloration syntaxique
syntax on

" Active l indentation syntaxique
set smartindent

" Show current mode
set showmode

" Show command being executed
set showcmd

" Always show status line
set laststatus=2"

" Enhance command line completion
set wildmenu

" Allow mouse use in vim
set mouse=a

" Briefly show matching braces, parens, etc
set showmatch

" Enable line wrapping
set wrap

" Wrap on column 80
set textwidth=79

" Disable preview window on completion
set completeopt=longest,menuone

" Highlight current line
set cursorline



"------------------------------------------------
" Search options
"------------------------------------------------

" Ignore case on search
set ignorecase

" Ignore case unless there is an uppercase letter in the pattern
set smartcase

" Move cursor to the matched string
set incsearch

" Indentation
filetype indent on



"------------------------------------------------
" Raccourci perso
"------------------------------------------------

" Indentation automatique < ;i >
nmap <silent> ;i gg=G
